# Generated by Django 3.2.8 on 2021-10-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_department', '0002_group_mtm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название оборудования')),
                ('model', models.CharField(max_length=200, verbose_name='Модель оборудования')),
                ('code', models.CharField(max_length=255, verbose_name='Инвентарный номер')),
                ('fk_cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.cabinet', verbose_name='Расположение оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
