# Generated by Django 3.2.8 on 2021-10-25 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_department', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(choices=[('', 'На месте'), ('н/б', 'Не был'), ('н/бу', 'Не был по уважительной причине')], default='', max_length=40, verbose_name='Присутствие')),
                ('mark', models.CharField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Удовлетворительно'), ('2', 'Не удовлетворительно'), ('', 'Нет оценки')], default='', max_length=20, verbose_name='Присутствие')),
                ('fk_dis_on_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.disciplineongroup', verbose_name='Занятие')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.RemoveField(
            model_name='educatordiscipline',
            name='fk_discipline',
        ),
        migrations.RemoveField(
            model_name='educatordiscipline',
            name='fk_user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='fk_part',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='EducatorDiscipline',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
