# Generated by Django 3.2.8 on 2021-10-27 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20211025_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата проведения занятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='check',
            field=models.CharField(choices=[('+', 'На месте'), ('н/б', 'Не был'), ('н/бу', 'Не был по уважительной причине')], default='+', max_length=40, verbose_name='Присутствие'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='mark',
            field=models.CharField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Удовлетворительно'), ('2', 'Не удовлетворительно'), ('-', 'Нет оценки')], default='-', max_length=20, verbose_name='Присутствие'),
        ),
    ]
