# Generated by Django 3.2.8 on 2021-10-25 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название кабинета')),
                ('number', models.CharField(max_length=15, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('semester', models.IntegerField(verbose_name='Номер семестра')),
                ('hours', models.FloatField(verbose_name='Часы')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Название отделения')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территории',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('fk_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.part', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='EducatorDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.discipline', verbose_name='Дисциплина')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Распределение дисциплины',
                'verbose_name_plural': 'Распределение дисциплин',
            },
        ),
        migrations.CreateModel(
            name='DisciplineOnGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.cabinet')),
                ('fk_edu_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.educatordiscipline')),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.group')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='fk_territoty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.territory', verbose_name='Название территории'),
        ),
    ]
