# Generated by Django 3.2.8 on 2021-10-25 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mtm_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
