# Generated by Django 3.2.8 on 2021-10-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_department', '0002_group_mtm_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinet',
            old_name='fk_territoty',
            new_name='fk_territory',
        ),
        migrations.AlterField(
            model_name='disciplineongroup',
            name='fk_cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.cabinet', verbose_name='Кабинет - территория'),
        ),
        migrations.AlterField(
            model_name='disciplineongroup',
            name='fk_edu_dis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.educatordiscipline', verbose_name='Преподаватель - дисциплина'),
        ),
        migrations.AlterField(
            model_name='disciplineongroup',
            name='fk_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_department.group', verbose_name='Группа'),
        ),
    ]
